Jumpstart.config = Jumpstart::Configuration.new({"application_name" => "Policy Pro",
 "business_name" => "Policy Pro",
 "business_address" => "",
 "domain" => "example.com",
 "support_email" => "support@example.com",
 "default_from_email" => "Policy Pro <no-reply@example.com>",
 "background_job_processor" => nil,
 "email_provider" => nil,
 "account_types" => "teams",
 "apns" => false,
 "fcm" => false,
 "integrations" => [],
 "omniauth_providers" => [],
 "payment_processors" => [],
 "multitenancy" => [],
 "gems" => []})
